<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SmartX.Wpf</RootNamespace>
    <AssemblyName>SmartX.Wpf</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartX.Core\SmartX.Core.csproj" />
    <ProjectReference Include="..\SmartX.Desktop.Client\SmartX.Desktop.Client.csproj" />
  </ItemGroup>

</Project>
